const pairs = [
  {url:'/calculo/calculadora-de-integrales', kw:'Calculadora de Integrales',
   title:'Calculadora de Integrales Online para el Cálculo Diferencial',
   desc:'Usa la Calculadora de Integrales para resolver integrales definidas e indefinidas. Ingresa la función, ajusta los límites y obtén el resultado paso a paso.'},
  {url:'/calculo/calculadora-de-derivadas', kw:'Calculadora de Derivadas',
   title:'Calculadora de Derivadas Online: Derivación y Pasos en Línea',
   desc:'Con la Calculadora de Derivadas puedes derivar funciones polinómicas, trigonométricas y compuestas online. Revisa reglas y el procedimiento con claridad.'},
  {url:'/calculo/calculadora-de-limites', kw:'Calculadora de Límites',
   title:'Calculadora de Límites Online: Evalúa Funciones al Instante',
   desc:'Usa la Calculadora de Límites para evaluar límites laterales y en el infinito. Introduce la función, el punto y obtén el resultado con los pasos claros.'},
  {url:'/calculo/calculadora-de-logaritmos', kw:'Calculadora de Logaritmos',
   title:'Calculadora de Logaritmos Online: Natural, Base 10 y Más Web',
   desc:'Con la Calculadora de Logaritmos calcula log base 10, logaritmo natural y cualquier base. Revisa la fórmula y el procedimiento paso a paso en español.'},
  {url:'/calculo/calculadora-de-exponentes', kw:'Calculadora de Exponentes',
   title:'Calculadora de Exponentes Online: Potencias y Radicales Web',
   desc:'Usa la Calculadora de Exponentes para calcular potencias, bases negativas y radicales. Obtén el resultado numérico con la fórmula y los pasos explicados.'},
  {url:'/algebra/calculadora-de-ecuaciones', kw:'Calculadora de Ecuaciones',
   title:'Calculadora de Ecuaciones Online: Lineales y Cuadráticas Web',
   desc:'Resuelve ecuaciones con la Calculadora de Ecuaciones. Introduce los coeficientes y obtén las soluciones con el procedimiento de despeje paso a paso.'},
  {url:'/algebra/calculadora-algebraica', kw:'Calculadora Algebraica',
   title:'Calculadora Algebraica Online: Simplifica Expresiones Fácil',
   desc:'La Calculadora Algebraica simplifica expresiones, factoriza polinomios y opera con variables. Ingresa la expresión y revisa el resultado con los pasos.'},
  {url:'/algebra/calculadora-de-polinomios', kw:'Calculadora de Polinomios',
   title:'Calculadora de Polinomios Online: Suma, Resta y Factoriza',
   desc:'Usa la Calculadora de Polinomios para sumar, restar, multiplicar y factorizar polinomios. Introduce los términos y obtén el resultado con procedimiento.'},
  {url:'/algebra/calculadora-de-raices', kw:'Calculadora de Raíces',
   title:'Calculadora de Raíces Online: Raíces Reales y Complejas Web',
   desc:'Encuentra raíces con la Calculadora de Raíces. Resuelve raíces cuadradas, cúbicas y n-ésimas. Obtén el resultado exacto o decimal con los pasos claros.'},
  {url:'/algebra/calculadora-de-raiz-cuadrada', kw:'Calculadora de Raíz Cuadrada',
   title:'Calculadora de Raíz Cuadrada Online: Exacta y Aproximada Web',
   desc:'Usa la Calculadora de Raíz Cuadrada para calcular raíces exactas y decimales. Introduce el número y obtén la raíz con el procedimiento explicado paso a paso.'},
  {url:'/matrices/calculadora-de-matrices', kw:'Calculadora de Matrices',
   title:'Calculadora de Matrices Online: Suma, Producto y Transpuesta',
   desc:'Usa la Calculadora de Matrices para sumar, multiplicar y transponer matrices. Introduce los valores, selecciona la operación y revisa el resultado completo.'},
  {url:'/matrices/calculadora-de-determinantes', kw:'Calculadora de Determinantes',
   title:'Calculadora de Determinantes Online: Matrices 2x2 y 3x3 Web',
   desc:'Calcula el determinante con la Calculadora de Determinantes. Introduce la matriz, elige el orden y obtén el resultado con el desarrollo paso a paso claro.'},
  {url:'/matrices/calculadora-de-vectores', kw:'Calculadora de Vectores',
   title:'Calculadora de Vectores Online: Suma, Módulo y Producto Web',
   desc:'Usa la Calculadora de Vectores para sumar, hallar el módulo y calcular el producto escalar. Introduce los componentes y obtén los resultados con los pasos.'},
  {url:'/matrices/calculadora-de-sistemas-de-ecuaciones', kw:'Calculadora de Sistemas de Ecuaciones',
   title:'Calculadora de Sistemas de Ecuaciones Online: 2x2 y 3x3',
   desc:'Resuelve sistemas con la Calculadora de Sistemas de Ecuaciones. Método de sustitución o eliminación. Introduce los coeficientes y obtén la solución clara.'},
  {url:'/matrices/calculadora-de-matriz-inversa', kw:'Calculadora de Matriz Inversa',
   title:'Calculadora de Matriz Inversa Online: Matrices 2x2 y 3x3 Web',
   desc:'Halla la inversa con la Calculadora de Matriz Inversa. Introduce los valores, verifica que el determinante sea distinto de cero y obtén la inversa al detalle.'},
  {url:'/aritmetica/calculadora-de-fracciones', kw:'Calculadora de Fracciones',
   title:'Calculadora de Fracciones Online: Suma, Resta y Simplifica',
   desc:'Usa la Calculadora de Fracciones para sumar, restar, multiplicar, dividir y simplificar. Introduce los numeradores y denominadores y obtén el resultado claro.'},
  {url:'/aritmetica/calculadora-de-porcentajes', kw:'Calculadora de Porcentajes',
   title:'Calculadora de Porcentajes Online: Descuentos y Aumentos Web',
   desc:'Con la Calculadora de Porcentajes calcula porcentaje de un valor, descuentos, aumentos y cambio porcentual. Introduce los datos y obtén el resultado al momento.'},
  {url:'/aritmetica/calculadora-cientifica', kw:'Calculadora Científica',
   title:'Calculadora Científica Online: Potencias, Raíces y Funciones',
   desc:'Usa la Calculadora Científica para resolver potencias, raíces, logaritmos, funciones trigonométricas y más. Ideal para operaciones matemáticas avanzadas online.'},
  {url:'/aritmetica/calculadora-de-regla-de-tres', kw:'Calculadora de Regla de Tres',
   title:'Calculadora de Regla de Tres Online: Directa e Inversa Web',
   desc:'Resuelve proporciones con la Calculadora de Regla de Tres. Introduce los valores conocidos y obtén el valor desconocido con el procedimiento paso a paso.'},
  {url:'/aritmetica/calculadora-de-promedio', kw:'Calculadora de Promedio',
   title:'Calculadora de Promedio Online: Media Aritmética de Valores',
   desc:'Usa la Calculadora de Promedio para calcular la media aritmética de un conjunto de datos. Introduce los valores, sepáralos con coma y obtén el promedio claro.'},
  {url:'/estadistica/calculadora-de-estadistica', kw:'Calculadora de Estadística',
   title:'Calculadora de Estadística Online: Resumen Descriptivo Rápido',
   desc:'Con la Calculadora de Estadística obtén media, mediana, moda, varianza y desviación estándar. Introduce los datos y revisa el resumen estadístico completo.'},
  {url:'/estadistica/calculadora-de-probabilidad', kw:'Calculadora de Probabilidad',
   title:'Calculadora de Probabilidad Online: Eventos y Combinaciones',
   desc:'Usa la Calculadora de Probabilidad para calcular probabilidad simple, combinaciones y permutaciones. Introduce los datos y obtén el resultado con los pasos.'},
  {url:'/estadistica/calculadora-de-desviacion-estandar', kw:'Calculadora de Desviación Estándar',
   title:'Calculadora de Desviación Estándar Online: Población y Muestra',
   desc:'Calcula con la Calculadora de Desviación Estándar la dispersión de datos de una muestra o población. Introduce los valores y obtén el resultado con pasos.'},
  {url:'/estadistica/calculadora-de-media', kw:'Calculadora de Media',
   title:'Calculadora de Media Online: Media Aritmética Paso a Paso Web',
   desc:'Usa la Calculadora de Media para obtener la media aritmética de un conjunto de valores. Introduce los datos separados por coma y revisa el cálculo completo.'},
  {url:'/estadistica/calculadora-de-varianza', kw:'Calculadora de Varianza',
   title:'Calculadora de Varianza Online: Población y Muestra en Línea',
   desc:'Calcula la varianza con la Calculadora de Varianza para muestras y poblaciones. Introduce los datos, obtén la varianza y revisa el procedimiento completo.'},
  {url:'/geometria/calculadora-de-area', kw:'Calculadora de Área',
   title:'Calculadora de Área Online: Figuras Geométricas Paso a Paso',
   desc:'Usa la Calculadora de Área para calcular áreas de rectángulos, triángulos, círculos y más figuras. Selecciona la forma, introduce las medidas y obtén el resultado.'},
  {url:'/geometria/calculadora-de-volumen', kw:'Calculadora de Volumen',
   title:'Calculadora de Volumen Online: Sólidos Geométricos en Línea',
   desc:'Con la Calculadora de Volumen calcula el volumen de cubos, esferas, cilindros y más sólidos. Introduce las medidas y obtén el resultado con la fórmula aplicada.'},
  {url:'/geometria/calculadora-de-triangulos', kw:'Calculadora de Triángulos',
   title:'Calculadora de Triángulos Online: Lados, Ángulos y Área Web',
   desc:'Usa la Calculadora de Triángulos para calcular lados, ángulos, área y perímetro. Introduce los datos conocidos y obtén las medidas faltantes con procedimiento.'},
  {url:'/geometria/calculadora-de-circulos', kw:'Calculadora de Círculos',
   title:'Calculadora de Círculos Online: Área, Radio y Circunferencia',
   desc:'Con la Calculadora de Círculos calcula área, circunferencia, diámetro y radio. Introduce un valor conocido y obtén todas las medidas del círculo al instante.'},
  {url:'/geometria/calculadora-de-pitagoras', kw:'Calculadora de Pitágoras',
   title:'Calculadora de Pitágoras Online: Teorema para Triángulos Web',
   desc:'Aplica el teorema con la Calculadora de Pitágoras. Introduce dos lados del triángulo rectángulo y obtén el tercer lado con la fórmula y el procedimiento claro.'}
];

let allPass = true;
pairs.forEach((p,i)=>{
  const tl = Array.from(p.title).length;
  const dl = Array.from(p.desc).length;
  const tkw = p.title.includes(p.kw);
  const dkw = p.desc.includes(p.kw);
  const pass = tl===60 && dl===160 && tkw && dkw;
  if(!pass) allPass = false;
  const status = pass ? 'OK  ' : 'FAIL';
  console.log(`${status} #${String(i+1).padStart(2)} T:${tl} D:${dl}${tkw?'':' !KW_T'}${dkw?'':' !KW_D'}  ${p.url}`);
});
console.log('');
console.log(allPass ? 'ALL 30 PASS' : 'FAILURES NEED FIXING');
